=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Clientes/ClientesV2/Clientes.dtd
<!ELEMENT Clientes (sede*)>
<!ELEMENT sede (direccion, empleado, fecha, cliente)>
    <!ATTLIST sede codigo CDATA #REQUIRED>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT empleado (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cliente (descripcion, numero, coste, resumen, plazo)>
    <!ATTLIST cliente codigo CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT coste (#PCDATA)>
<!ELEMENT resumen (#PCDATA)>
<!ELEMENT plazo (#PCDATA)>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Clientes/ClientesV2/ClientesRefDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Clientes SYSTEM "Clientes.dtd">
<Clientes>
<sede codigo = "J7558575">
    <direccion>C/Marroquineros</direccion>
    <empleado>Antonio Recio</empleado>
    <fecha>12-06-2015</fecha>
    <cliente codigo = "HGJ-747">
        <descripcion>Solvente</descripcion>
        <numero>1</numero>
        <coste>345</coste>
        <resumen>Buena vivienda en zona centrica</resumen>
        <plazo>21</plazo>
    </cliente>
</sede>

<sede codigo = "R7848938">
    <direccion>C/Remedios</direccion>
    <empleado>Vicente del Bosque</empleado>
    <fecha>28-08-2017</fecha>
    <cliente codigo = "UFT-808">
        <descripcion>Insolvente</descripcion>
        <numero>3</numero>
        <coste>123</coste>
        <resumen>Vivienda situada en las afueras</resumen>
        <plazo>14</plazo>
    </cliente>
</sede>

<sede codigo = "M6469278">
    <direccion>C/Agua</direccion>
    <empleado>Nil Ojeda</empleado>
    <fecha>14-04-2018</fecha>
    <cliente codigo = "YHU-649">
        <descripcion>Insolvente</descripcion>
        <numero>2</numero>
        <coste>210</coste>
        <resumen>Vivienda amplia y muy familiar</resumen>
        <plazo>13</plazo>
    </cliente>
</sede>

<sede codigo = "F5358590">
    <direccion>C/Sol</direccion>
    <empleado>Dani Güiza</empleado>
    <fecha>27-04-2019</fecha>
    <cliente codigo = "UUK-838">
        <descripcion>Solvente</descripcion>
        <numero>1</numero>
        <coste>67</coste>
        <resumen>Vivienda pequeña ideal para estudiante</resumen>
        <plazo>16</plazo>
    </cliente>
</sede>

<sede codigo = "E2847562">
    <direccion>C/Almería</direccion>
    <empleado>Pedro Benito</empleado>
    <fecha>31-11-2021</fecha>
    <cliente codigo = "TDI-622">
        <descripcion>Insolvente</descripcion>
        <numero>4</numero>
        <coste>200</coste>
        <resumen>Buena vivienda con terraza y vista al mar</resumen>
        <plazo>23</plazo>
    </cliente>
</sede>
</Clientes>
