=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Practicas CFGS/mejora.dtd
<!ELEMENT jugadores (jugador*)>
<!ELEMENT jugador (nombre, dorsal, salud, fecha_primer_gol*, (portero | defensa | medio | delantero))>
    <!ATTLIST jugador equipo CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dorsal (#PCDATA)>
<!ELEMENT salud (#PCDATA)>
<!ELEMENT fecha_primer_gol (#PCDATA)>
<!ELEMENT portero (#PCDATA)>
<!ELEMENT defensa (#PCDATA)>
<!ELEMENT medio (#PCDATA)>
<!ELEMENT delantero (#PCDATA)>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Practicas CFGS/mejoraRefDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jugadores SYSTEM "mejora.dtd">
<jugadores>
    <jugador equipo= "Real Betis">
        <nombre>Germán Pezzella</nombre>
        <dorsal>16</dorsal>
        <salud>En forma</salud>
        <fecha_primer_gol>12/03/2017</fecha_primer_gol>
        <defensa>central</defensa>
    </jugador>
    <jugador equipo="Cádiz CF">
        <nombre>Brian Ocampo</nombre>
        <dorsal>14</dorsal>
        <salud>En Forma</salud>
        <delantero>Extremo Izquierdo</delantero>
    </jugador>
</jugadores>
