=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Practicas CFGS/mejoraSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    version="0.1" xml:lang="es">
    <xs:element name="jugadores" >
        <xs:complexType>
            <xs:sequence>
                <xs:element name="jugador"  maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="dorsal" type="xs:string"/>
                            <xs:element name="salud" type="xs:string"/>
                            <xs:element name="fecha_primer_gol" type="xs:string"/>
                            <xs:choice>
                                <xs:element name="portero" type="xs:string"/>
                                <xs:element name="defensa" type="xs:string"/>
                                <xs:element name="medio" type="xs:string"/>
                                <xs:element name="delantero" type="xs:string"/>
                            </xs:choice>
                        </xs:sequence>
                        <xs:attribute name="equipo" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="equipo">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
</xs:schema>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Practicas CFGS/mejora.xml
<?xml version="1.0" encoding="UTF-8"?>
<jugadores xmlns:xsi="http://www.w3.org/2001/XMLSchema" 
xsi:noNamespaceSchemaLocation="mejoraSchema.xsd">
    <jugador equipo= "Real Betis">
        <nombre>Germán Pezzella</nombre>
        <dorsal>16</dorsal>
        <salud>En forma</salud>
        <fecha_primer_gol>12/03/2017</fecha_primer_gol>
        <defensa>central</defensa>
    </jugador>
    <jugador equipo="Cádiz CF">
        <nombre>Brian Ocampo</nombre>
        <dorsal>14</dorsal>
        <salud>En Forma</salud>
        <delantero>Extremo Izquierdo</delantero>
    </jugador>
    <jugador equipo= "Valencia FC">
        <nombre>Hugo Guillamón</nombre>
        <dorsal>4</dorsal>
        <salud>Lesionado</salud>
        <fecha_primer_gol>2/10/2022</fecha_primer_gol>
        <medio>pivote defensivo</medio>
    </jugador>
</jugadores>
