=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Biblioteca/Mejora.dtd
<!ELEMENT Mejora (pelicula*)>
<!ELEMENT pelicula (titulo, titulo_original, productora, duracion, fecha_estreno, directores, actores, genero)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT titulo_original (#PCDATA)>
<!ELEMENT productora (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT fecha_estreno (año)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT directores (director)>
<!ELEMENT director (nombre, apellido)>
<!ELEMENT actores (actor)>
<!ELEMENT actor (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT genero (#PCDATA)>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Biblioteca/MejoraRefDTD.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mejora SYSTEM "Mejora.dtd">
<Mejora>
    <pelicula>
        <titulo>Sin Remordimientos</titulo>
        <titulo_original>Without Remorse</titulo_original>
        <productora>Amazon Studios</productora>
        <duracion>110 min.</duracion>
        <fecha_estreno>
            <año>2021</año>
        </fecha_estreno>
        <directores>
            <director>
                <nombre>Stefano</nombre>
                <apellido>Sollima</apellido>
            </director>
        </directores>
        <actores>
            <actor>
                <nombre>Michael B.</nombre>
                <apellido>Jordan</apellido>
            </actor>
        </actores>
        <genero>Acción</genero>
    </pelicula>

</Mejora>
