=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Biblioteca/MejoraSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="Mejora">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pelicula" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="titulo_original" type="xs:string"/>
                            <xs:element name="productora" type="xs:string"/>
                            <xs:element name="duracion" type="xs:string"/>
                            <xs:element name="fecha_estreno" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="aÃ±o" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="director" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellido" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="actores" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="actor" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="apellido" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="duracion" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Biblioteca/Mejora.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mejora xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="MejoraSchema.xsd">
    <pelicula>
        <titulo>Sin Remordimientos</titulo>
        <titulo_original>Without Remorse</titulo_original>
        <productora>Amazon Studios</productora>
        <duracion>110 min.</duracion>
        <fecha_estreno>
            <año>2021</año>
        </fecha_estreno>
        <directores>
            <director>
                <nombre>Stefano</nombre>
                <apellido>Sollima</apellido>
            </director>
        </directores>
        <actores>
            <actor>
                <nombre>Michael B.</nombre>
                <apellido>Jordan</apellido>
            </actor>
        </actores>
        <genero>Acción</genero>
    </pelicula>

</Mejora>
