=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Clientes/ClientesSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
    <xs:element name="Clientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sede" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="codigo_sede" type="xs:string"/>
                            <xs:element name="empleado" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="apellido" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="fecha" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" type="xs:string"/>
                                        <xs:element name="mes" type="xs:string"/>
                                        <xs:element name="año" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="descripcion" type="xs:string"/>
                            <xs:element name="cliente" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="codigo_cliente" type="xs:string"/>
                                        <xs:element name="numero_viviendas" type="xs:string"/>
                                        <xs:element name="coste_viviendas" type="xs:string"/>
                                        <xs:element name="resumen_viviendas" type="xs:string"/>
                                        <xs:element name="plazo_alta" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dia" type="xs:string"/>
                                                    <xs:element name="mes" type="xs:string"/>
                                                    <xs:element name="año" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Clientes/ClientesOriginal/Clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="ClientesSchema.xsd">
    <sede>
        <codigo_sede>S8570378</codigo_sede>
        <empleado>
            <nombre>Juan</nombre>
            <apellido>Cruz</apellido>
        </empleado>
        <fehca>
            <dia>17</dia>
            <mes>01</mes>
            <año>2017</año>
        </fehca>
        <descripcion>Solvente</descripcion>
        <cliente>
            <codigo_cliente>HFJ-748</codigo_cliente>
            <numero_viviendas>1</numero_viviendas>
            <coste_vivienda>237.000</coste_vivienda>
            <resumen_vivienda>80 m^2</resumen_vivienda>
            <plazo_alta>
                <dia>17</dia>
                <mes>02</mes>
                <año>2017</año>
            </plazo_alta>
        </cliente>
    </sede>

    <sede>
        <codigo_sede>G7859023</codigo_sede>
        <empleado>
            <nombre>Joaquín</nombre>
            <apellido>Sanchez</apellido>
        </empleado>
        <fehca>
            <dia>23</dia>
            <mes>08</mes>
            <año>2019</año>
        </fehca>
        <descripcion>Solvente</descripcion>
        <cliente>
            <codigo_cliente>PDO-749</codigo_cliente>
            <numero_viviendas>1</numero_viviendas>
            <coste_vivienda>456.000</coste_vivienda>
            <resumen_vivienda>156 m^2</resumen_vivienda>
            <plazo_alta>
                <dia>23</dia>
                <mes>09</mes>
                <año>2019</año>
            </plazo_alta>
        </cliente>
    </sede>

    <sede>
        <codigo_sede>I7580125</codigo_sede>
        <empleado>
            <nombre>Pablo</nombre>
            <apellido>Chacón</apellido>
        </empleado>
        <fehca>
            <dia>30</dia>
            <mes>07</mes>
            <año>2020</año>
        </fehca>
        <descripcion>Insolvente</descripcion>
        <cliente>
            <codigo_cliente>LKD-193</codigo_cliente>
            <numero_viviendas>1</numero_viviendas>
            <coste_vivienda>259.000</coste_vivienda>
            <resumen_vivienda>102 m^2</resumen_vivienda>
            <plazo_alta>
                <dia>30</dia>
                <mes>08</mes>
                <año>2020</año>
            </plazo_alta>
        </cliente>
    </sede>
</Clientes>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Clientes/Clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="ClientesSchema.xsd">
    <sede>
        <codigo_sede></codigo_sede>
        <empleado></empleado>
        <fehca>
            <dia></dia>
            <mes></mes>
            <año></año>
        </fehca>
        <descripcion></descripcion>
        <cliente>
            <codigo_cliente></codigo_cliente>
            <numero_viviendas></numero_viviendas>
            <coste_vivienda></coste_vivienda>
            <resumen_vivienda></resumen_vivienda>
            <plazo_alta></plazo_alta>
        </cliente>
    </sede>

</Clientes>
