=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Concesionario/MejoraSchema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="0.1" xml:lang="es">
<xs:element name="Mejora">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="prenda" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="codigo_prenda" type="xs:string"/>
                        <xs:element name="tipo_prenda" type="xs:string"/>
                        <xs:element name="marca" type="xs:string"/>
                        <xs:element name="coleccion" type="xs:string"/>
                        <xs:element name="talla" type="xs:string"/>
                        <xs:element name="stock" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>                
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== 2010jmatpon/JuanMariaMateosPonce_UD4_LMSGI/Concesionario/Mejora.xml
<?xml version="1.0" encoding="UTF-8"?>
<Mejora xmlns:xsi="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="MejoraSchema.xsd">
    <prenda>
        <codigo_prenda>#1</codigo_prenda>
        <tipo_prenda>Camiseta</tipo_prenda>
        <marca>Adidas</marca>
        <coleccion>Primavera-Verano</coleccion>
        <talla>L</talla>
        <stock>25</stock>
    </prenda>

    <prenda>
        <codigo_prenda>#2</codigo_prenda>
        <tipo_prenda>Short</tipo_prenda>
        <marca>Adidas</marca>
        <coleccion>Primavera-Verano</coleccion>
        <talla>S</talla>
        <stock>7</stock>
    </prenda>

    <prenda>
        <codigo_prenda>#3</codigo_prenda>
        <tipo_prenda>Pantalón</tipo_prenda>
        <marca>Jordan</marca>
        <coleccion>Otoño_Invierno</coleccion>
        <talla>XL</talla>
        <stock>12</stock>
    </prenda>

    <prenda>
        <codigo_prenda>#4</codigo_prenda>
        <tipo_prenda>Top</tipo_prenda>
        <marca>Nike</marca>
        <coleccion>Primavera-Verano</coleccion>
        <talla>M</talla>
        <stock>22</stock>
    </prenda>

    <prenda>
        <codigo_prenda>#5</codigo_prenda>
        <tipo_prenda>Gorro</tipo_prenda>
        <marca>New Era</marca>
        <coleccion>Otoño-Invierno</coleccion>
        <talla>Única</talla>
        <stock>10</stock>
    </prenda>
</Mejora>
